// Generated by CoffeeScript 1.6.2
(function() {
  var canvasPaint, canvasVideo, facePaint, getElements, img, init, paintContext, setElementSizes, setEventListeners, videoInput, windowHeight, windowWidth;

  videoInput = null;

  canvasVideo = null;

  canvasPaint = null;

  paintContext = null;

  img = null;

  windowHeight = window.innerHeight;

  windowWidth = window.innerWidth;

  getElements = function() {
    videoInput = document.getElementById('input-video');
    canvasVideo = document.getElementById('canvas-video');
    canvasPaint = document.getElementById('canvas-paint');
    img = document.getElementById('img');
    paintContext = canvasPaint.getContext('2d');
  };

  setElementSizes = function() {
    windowHeight = window.innerHeight;
    windowWidth = window.innerWidth;
    videoInput.style.height = windowHeight;
    videoInput.style.width = windowWidth;
    canvasVideo.style.height = windowHeight;
    canvasVideo.style.width = windowWidth;
    canvasPaint.style.height = windowHeight;
    canvasPaint.style.width = windowWidth;
  };

  setEventListeners = function() {
    document.addEventListener('facetrackingEvent', function(event) {
      console.log(event.height);
      facePaint(event.height, event.width, event.angle, event.x, event.y);
    });
    window.onresize = function() {
      return setElementSizes();
    };
    window.addEventListener('onresize', function() {
      return setElementSizes();
    });
  };

  facePaint = function(height, width, angle, x, y) {
    paintContext.clearRect(0, 0, windowWidth, windowHeight);
    paintContext.drawImage(img, x - (width / 2), y - (height / 2), width, height);
  };

  init = function() {
    var htracker;

    getElements();
    setElementSizes();
    setEventListeners();
    htracker = new headtrackr.Tracker({
      ui: false
    });
    htracker.init(videoInput, canvasVideo);
    htracker.start();
  };

  init();

}).call(this);
